#!/bin/bash


#training
MMF_USER_DIR="." mmf_run config="configs/experiments/defaults.yaml" model=simple_baseline dataset=clevr run_type=train_val training.batch_size=128

#local
mmf_run config="configs/experiments/local.yaml" model=simple_baseline dataset=clevr run_type=train_val training.batch_size=128

#resume training
MMF_USER_DIR="." mmf_run config="configs/experiments/defaults.yaml" model=simple_baseline dataset=clevr \
 run_type=train_val training.batch_size=128 checkpoint.resume=True


#evaluating
MMF_USER_DIR="." mmf_run config="configs/experiments/defaults.yaml" \
    model=simple_baseline \
    dataset=clevr \
    run_type=val \
    checkpoint.resume=True \
    checkpoint.resume_best=True

