model_config:
  vqa_transformer:
    image_hidden_size: 2048
    num_segment_type: 2
    hidden_size: 512
    num_hidden_layers: 9
    num_attention_heads: 8
    intermediate_size: 2048
    hidden_act: "gelu"
    hidden_dropout_prob: 0.1
    layer_norm_eps: 1e-12

    losses:
    - type: cross_entropy

    text_embedding:
      embedding_dim: 300
    lstm:
      input_size: 300
      hidden_size: ${model_config.vqa_transformer.hidden_size}
      bidirectional: true
      batch_first: true
