model_config:
  simple_baseline:
    losses:
    - type: logit_bce
    text_embedding:
      embedding_dim: 300
    lstm:
      input_size: 300
      hidden_size: 512
      bidirectional: true
      batch_first: true
    image_encoder:
      type: resnet152
      params:
        pretrained: true
        pool_type: avg
        num_output_features: 1
    classifier:
      type: mlp
      params:
        in_dim: 450
        out_dim: 2