model_config:
  mac_network:
    freeze_visual: true
    dimension: 512
    losses:
    - type: logit_bce
    text_embedding:
      embedding_dim: 300
    lstm:
      input_size: 300
      hidden_size: 512
      bidirectional: true
      batch_first: true
    mac_unit:
      max_step: 4
      self_attention: False
      memory_gate: False
      dim: 512
    image_encoder:
      type: resnet101
      params:
        pretrained: true
    classifier:
      type: mlp
      params:
        in_dim: 1536
        out_dim: 2
        num_layers: 1