model_config:
  mac_network:
    dimension: 2048
    losses:
    - type: logit_bce
    text_embedding:
      embedding_dim: 300
    lstm:
      input_size: 300
      hidden_size: 2048
      bidirectional: true
      batch_first: true
    mac_unit:
      max_step: 4
      self_attention: False
      memory_gate: False
      dim: 2048
    classifier:
      type: mlp
      params:
        in_dim: 6144
        out_dim: 2
        num_layers: 1